### ISSUE TITLE
If user uses wrong image in deployment but used `--deployment` option, error is confusing.

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#121]
### What were you trying to do?

Run Telepresence against existing deployment, but I'd used wrong image name so it wasn't findable.

### What did you expect to happen?

Meaningful error: "can't find any pods running the expected image `datawire/telepresence-k8s:0.41`, perhaps there's a typo in your Deployment spec?"

### What happened instead?

Crash.

### Automatically included information

Command line: `['/home/itamarst/bin/telepresence', '--deployment', 'myserver', '--expose', '8080', '--run-shell']`
Version: `0.41`
Python version: `3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609]`
kubectl version: `Client Version: v1.6.0`
OS: `Linux hexagon 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/home/itamarst/bin/telepresence", line 765, in call_f
    return f(*args, **kwargs)
  File "/home/itamarst/bin/telepresence", line 885, in go
    runner, args
  File "/home/itamarst/bin/telepresence", line 540, in start_proxy
    runner, args.deployment, args.context, args.namespace
  File "/home/itamarst/bin/telepresence", line 358, in get_remote_info
    deployment,
  File "/home/itamarst/bin/telepresence", line 229, in __init__
    ][0]
IndexError: list index out of range

```

Logs:

```
Running: (['kubectl', 'cluster-info'],)
Running 'ssh -V'...Running: (['which', 'torsocks'],)
Running: (['which', 'sshfs'],)
Running: (['kubectl', 'get', 'deployment', '-o', 'json', 'myserver', '--export'],)
Expected metadata for pods: {'creationTimestamp': None, 'labels': {'run': 'myserver'}}
Running: (['kubectl', 'get', 'pod', '-o', 'json', '--export'],)
Checking {'run': 'mynginx', 'pod-template-hash': '2077887059'} (phase Running)...
Labels don't match.
Checking {'run': 'myserver', 'pod-template-hash': '1178015049'} (phase Pending)...
Looks like we've found our pod!

```

**Comment by itamarst** [comment]
If Deployment is non-existent there's also a traceback, but an easier one to understand.
