### ISSUE TITLE
Swapping container gives "invalid field terminationMessagePolicy for v1.Container"

### ISSUE THREAD

**Issue by vincentvanderweele** [datawire/telepresence#265]
### What were you trying to do?

Swapping a local container with one in a remote kubernetes cluster on OSX. This might be related to #226?

### What did you expect to happen?

The container is swapped successfully

### What happened instead?

I get the below error instead

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '-m', 'container', '--swap-deployment', 'gateway-service', '--expose', '3000', '--docker-run', '--rm', '-it', '-v', '/Users/vwee/go/src/github.com/xxx/gateway-service:/go/src/github.com/xxx/gateway-service', 'xxx/gateway-service', 'sh', '-c', 'export AUTH_JWT_KEY_FILE=$TELEPRESENCE_ROOT/etc/.ssh/authkey.pub && fresh']`
Version: `0.63`
Python version: `3.6.2 (default, Jul 17 2017, 16:44:47) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
kubectl version: `Client Version: v1.7.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin 141192236011.edelkey.net 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 133, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2177, in go
    runner, args
  File "/usr/local/bin/telepresence", line 1335, in start_proxy
    runner, args
  File "/usr/local/bin/telepresence", line 1144, in swap_deployment
    apply_json(new_deployment_json)
  File "/usr/local/bin/telepresence", line 1123, in apply_json
    input=json.dumps(json_config).encode("utf-8")
  File "/usr/local/bin/telepresence", line 275, in check_kubectl
    self.kubectl(context, namespace, kubectl_args), **kwargs
  File "/usr/local/bin/telepresence", line 228, in check_call
    **kwargs
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'default-system', '--namespace', 'default', 'apply', '-f', '-']' returned non-zero exit status 1.

```

Logs:

```
Context: default-system, namespace: default, kubectl_command: kubectl
Running: (['kubectl', '--context', 'default-system', 'cluster-info'],)... ran!
Running 'ssh -V'...Running: (['which', 'torsocks'],)... ran!
Running: (['which', 'sshfs'],)... ran!
Running: (['kubectl', '--context', 'default-system', '--namespace', 'default', 'get', 'deployment', '-o', 'json', '--export', 'gateway-service'],)... ran!
Running: (['kubectl', '--context', 'default-system', '--namespace', 'default', 'delete', 'deployment', 'gateway-service'],)... deployment "gateway-service" deleted
 ran!
Running: (['kubectl', '--context', 'default-system', '--namespace', 'default', 'apply', '-f', '-'],)... error: error validating "STDIN": error validating data: found invalid field terminationMessagePolicy for v1.Container; if you choose to ignore these errors, turn validation off with --validate=false

```

**Comment by vincentvanderweele** [comment]
I just verified that the problem does not occur with version 0.58. I downgraded now so I can continue using telepresence 👍

**Comment by ark3** [comment]
Thanks for the bug report and the workaround. What versions of Kubernetes are you running? 

```shell
$ kubectl version --short
Client Version: v1.7.2
Server Version: v1.7.0
```

**Comment by vincentvanderweele** [comment]
Ah, that could well be the problem, we're running a relatively old version on the server:

```
$ kubectl version --short
Client Version: v1.7.0
Server Version: v1.5.6
```

Should that version be supported still or are my options to keep the downgraded version of telepresence or upgrade kubernetes?

**Comment by ark3** [comment]
Adding a version check so that you can run the latest Telepresence shouldn't be a problem as long as it's just things like extra fields (`terminationMessagePolicy` in this case) that are causing the incompatibility. Stay tuned!

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
