### ISSUE TITLE
Cannot run dev telepresence on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by richarddli** [datawire/telepresence#277]
### What were you trying to do?

run telepresence out of github with Kubernaut

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['./cli/telepresence']`
Version: `0.65-1-g62b8436`
Python version: `3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]`
kubectl version: `Client Version: v1.7.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Jesss-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "./cli/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "./cli/telepresence", line 2314, in go
    runner, args
  File "./cli/telepresence", line 1483, in start_proxy
    run_id=run_id,
  File "./cli/telepresence", line 861, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "./cli/telepresence", line 1013, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2017-08-30T13:09:21Z', 'status': 'True', 'type': 'Initialized'}, {'lastProbeTime': None, 'lastTransitionTime': '2017-08-30T13:09:21Z', 'message': 'containers with unready status: [telepresence-1504098560-34761-23510]', 'reason': 'ContainersNotReady', 'status': 'False', 'type': 'Ready'}, {'lastProbeTime': None, 'lastTransitionTime': '2017-08-30T13:09:21Z', 'status': 'True', 'type': 'PodScheduled'}], 'containerStatuses': [{'image': 'datawire/telepresence-k8s:0.65-1-g62b8436', 'imageID': '', 'lastState': {}, 'name': 'telepresence-1504098560-34761-23510', 'ready': False, 'restartCount': 0, 'state': {'waiting': {'message': 'rpc error: code = 2 desc = Error response from daemon: {"message":"manifest for datawire/telepresence-k8s:0.65-1-g62b8436 not found"}', 'reason': 'ErrImagePull'}}}], 'hostIP': '10.10.2.211', 'phase': 'Pending', 'podIP': '192.168.127.194', 'qosClass': 'Burstable', 'startTime': '2017-08-30T13:09:21Z'}

```

Logs:

```
es', '--namespace', 'default', 'get', 'pod', 'telepresence-1504098560-34761-23510-1791570504-jzbx6', '-o', 'json'],)... ran!
Running: (['kubectl', '--context', 'admin@kubernetes', '--namespace', 'default', 'get', 'pod', 'telepresence-1504098560-34761-23510-1791570504-jzbx6', '-o', 'json'],)... ran!
Running: (['kubectl', '--context', 'admin@kubernetes', '--namespace', 'default', 'get', 'pod', 'telepresence-1504098560-34761-23510-1791570504-jzbx6', '-o', 'json'],)... ran!
Running: (['kubectl', '--context', 'admin@kubernetes', '--namespace', 'default', 'get', 'pod', 'telepresence-1504098560-34761-23510-1791570504-jzbx6', '-o', 'json'],)... ran!
Running: (['kubectl', '--context', 'admin@kubernetes', '--namespace', 'default', 'get', 'pod', 'telepresence-1504098560-34761-23510-1791570504-jzbx6', '-o', 'json'],)... ran!
Running: (['kubectl', '--context', 'admin@kubernetes', '--namespace', 'default', 'get', 'pod', 'telepresence-1504098560-34761-23510-1791570504-jzbx6', '-o', 'json'],)... ran!

```

**Comment by richarddli** [comment]
So on this Mac 10.12.6, I can run telepresence 0.65 out of homebrew successfully with Kubernaut.
I cannot run it with `master`.

On a different Mac running 10.11.6, I can run telepresence 0.65 out of homebrew successfully with Kubernaut. I cannot run it with `master`. However, I *can* run `master` successfully with GKE.

**Comment by richarddli** [comment]
This is because I'm not pushing docker images.
