### ISSUE TITLE
Failure deploying using docker-run

### ISSUE THREAD

**Issue by snowe2010** [datawire/telepresence#399]
### What were you trying to do?

```
docker build -t test .
telepresence --swap-deployment gateway --docker-run --rm -it -v $(pwd):/service test:latest
```

I believe this happened due to the `$(pwd):/service` bit. I do not know what that does, so I'm assuming it's due to some file missing. 

### What did you expect to happen?

Deploy my gateway service (with docker tag `test`) to telepresence

### What happened instead?

The trace below

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'gateway', '--docker-run', '--rm', '-it', '-v', '/Users/tylerthrailkill/Documents/dev/code/backend/gateway:/service', 'test:latest']`
Version: `0.71`
Python version: `3.6.3 (default, Oct  4 2017, 06:09:15) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.8.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin ip-172-16-8-137.ec2.internal 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 259, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2386, in go
    runner, args
  File "/usr/local/bin/telepresence", line 1538, in start_proxy
    processes, socks_port, ssh = connect(runner, remote_info, args)
  File "/usr/local/bin/telepresence", line 1173, in connect
    ), "TCP4:127.0.0.1:{}".format(ssh.port)
  File "/usr/local/bin/telepresence", line 406, in popen
    return self.launch_command(track, *args, **kwargs)
  File "/usr/local/bin/telepresence", line 360, in launch_command
    process = Popen(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'socat': 'socat'

```

Logs:

```
000 [socks.SOCKSv5Factory#info] Starting factory <socks.SOCKSv5Factory object at 0x7f176a0deb00>
  22.5 40 | 2018-01-09T17:05:34+0000 [-] /etc/resolv.conf changed, reparsing
  22.5 40 | 2018-01-09T17:05:34+0000 [-] Resolver added ('10.47.240.10', 53) to server list
  22.5 40 | 2018-01-09T17:05:34+0000 [-] DNSDatagramProtocol starting on 9053
  22.5 40 | 2018-01-09T17:05:34+0000 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f176a0f2dd8>
  22.5 40 | 2018-01-09T17:05:34+0000 [-] Loaded.
  22.6 40 | 2018-01-09T17:05:34+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.9.0 (/usr/bin/python3.6 3.6.1) starting up.
  22.6 40 | 2018-01-09T17:05:34+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
  22.6 41 | Forwarding from 127.0.0.1:53845 -> 8022
  28.0 TL | [42] ran.
  28.0 TL | [43] Launching: (['socat', 'TCP4-LISTEN:53845,bind=198.18.0.254,reuseaddr,fork', 'TCP4:127.0.0.1:53845'],)...

```

**Comment by richarddli** [comment]
Does the `docker run` command work on its own?

(The `-v` bit mounts your local filesystem into the `/service/` directory in your Docker container, so you can edit your code locally and have it live reload in the Docker container.)

**Comment by richarddli** [comment]
Needed to install `socat`

**Comment by exarkun** [comment]
Looks related to #336
