### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by dhensen** [datawire/telepresence#452]
### What were you trying to do?

A few months ago I integrated telepresence in our custom tooling. It calls telepresence like this:
`telepresence --swap-deployment {deployment_name}:{container_name} --context {context} --namespace {namespace} --run-shell`. It fails on my laptop running Arch Linux using 0.71 and 0.75. On my work computer running Ubuntu 16.04 LTS it works fine running 0.73. It was working before on my laptop where I did most of the telepresence integration work.

I then manually tried a stripped down version of the command in my shell:
```
telepresence --swap-deployment match-runner --run-shell
```

### What did you expect to happen?

To give me telepresence shell.

### What happened instead?

The traceback happened.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'match-runner', '--run-shell']`
Version: `0.75`
Python version: `3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224]`
kubectl version: `Client Version: v1.6.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux liekaliek 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 241, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 230, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence134')"]' returned non-zero exit status 1.

```

Logs:

```
me or service not known
  27.2 TL | [155] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence131')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  27.4 TL | [156] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence132')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  27.5 TL | [157] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence133')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  27.7 TL | [158] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence134')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by dhensen** [comment]
I remember having had a similar problem #297. It was related to some kernel module stuff after rebooting. I checked the iptables command from that issue, but that was not the problem this time. I rebooted anyways... and now it works again......

**Comment by ark3** [comment]
Thank you for the information. Could you send me the full telepresence.log from a failing run like this one? I understand that we'll have to wait for another kernel update before you can reproduce this. I only ask because it would be great if Telepresence could somehow detect the problem and let you know in some manner besides a crash. I'd like to look for any telltale signs in the log output. Thanks!
