### ISSUE TITLE
crash reporter test

### ISSUE THREAD

**Issue by ark3** [datawire/telepresence#565]
### What were you trying to do?

Test the crash reporter

### What did you expect to happen?

This crash window

### What happened instead?

Just what I expected

### Automatically included information

Command line: `['/Users/ark3/datawire/bin/telepresence', '--docker-run', '--rm', '-it', 'alpine', 'wget', '-qO-', 'qotm']`
Version: `0.78`
Python version: `3.6.4 (default, Mar  9 2018, 23:15:03) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.9.6 // Server Version: v1.7.14-gke.1`
oc version: `oc v3.7.2+282e43f // kubernetes v1.7.6+a08f5eeb62 // features: Basic-Auth //  // Server https://35.184.12.241 // kubernetes v1.7.14-gke.1`
OS: `Darwin timonium.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/Users/ark3/datawire/telepresence/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/Users/ark3/datawire/telepresence/telepresence/main.py", line 489, in go_too
    require_command(runnerx, "sshfs")
NameError: name 'runnerx' is not defined

```

Logs:

```
:15:03)
   0.0 TEL | [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
   0.0   3 | Darwin timonium.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
   0.0 TEL | [3] exit 0
   0.1 TEL | BEGIN SPAN main.py:418(go_too)
   0.1 TEL | Scout info: {'latest_version': '0.78', 'application': 'telepresence', 'notices': []}
   0.1 TEL | Context: gke_datawireio_us-central1-a_telepresence-testing, namespace: default, kubectl_command: kubectl
   0.1 TEL | [4] Capturing: kubectl --context gke_datawireio_us-central1-a_telepresence-testing cluster-info
   0.3   1 | Client Version: v1.9.6
   0.3   1 | Server Version: v1.7.14-gke.1
   0.3 TEL | [1] exit 0
   0.4 TEL | [5] Capturing: ssh -V
   0.4 TEL | [6] Capturing: which torsocks
   0.5   2 | oc v3.7.2+282e43f
   0.5   2 | kubernetes v1.7.6+a08f5eeb62
   0.5   2 | features: Basic-Auth
   0.7   2 | 
   0.7   2 | Server https://35.184.12.241
   0.7   2 | kubernetes v1.7.14-gke.1

```

**Comment by ark3** [comment]
Yay, it worked!
