### ISSUE TITLE
Crash when starting telepresence

### ISSUE THREAD

**Issue by nigorice** [datawire/telepresence#577]
### What were you trying to do?

Following getting started guide outlined in https://asciinema.org/a/117761

```
$ telepresence --deployment myserver --expose 8080 --run-shell
```

### What did you expect to happen?

Connect to proxy of k8s cluster

### What happened instead?

Crash

### Automatically included information

Command line: `['/opt/telepresence/telepresence-venv/bin/telepresence', '--deployment', 'myserver', '--expose', '8080', '--run-shell']`
Version: `0.76`
Python version: `3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224]`
kubectl version: `Client Version: v1.8.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux scl3a3-4 4.14.30-1-MANJARO #1 SMP PREEMPT Sun Mar 25 19:47:20 UTC 2018 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/main.py", line 501, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/vpn.py", line 223, in connect_sshuttle
    runner, args, remote_info, env["KUBERNETES_SERVICE_HOST"]
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 177, in popen
    result = self.launch_command(track, args, **kwargs)
  File "/opt/telepresence/telepresence-venv/lib/python3.6/site-packages/telepresence/runner.py", line 126, in launch_command
    process = Popen(args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sshuttle-telepresence': 'sshuttle-telepresence'

```

Logs:

```
74-3337']...
  10.1 31 | service "telepresence-1523348877-673874-3337" deleted
  10.1 TL | [31] ran.
  10.1 TL | [32] Running: ['kubectl', 'delete', 'service', 'telepresence-1523348877-9170876-3337']...
  10.8 32 | service "telepresence-1523348877-9170876-3337" deleted
  10.8 TL | [32] ran.
  10.8 TL | [33] Running: ['kubectl', 'delete', 'service', 'telepresence-1523348878-132999-3337']...
  11.1 33 | service "telepresence-1523348878-132999-3337" deleted
  11.2 TL | [33] ran.
  11.2 TL | END SPAN vpn.py:70(get_proxy_cidrs)    5.9s
  11.2 TL | [34] Launching: ['sshuttle-telepresence', '-v', '--dns', '--method', 'nat', '-e', 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -F /dev/null', '--to-ns', '127.0.0.1:9053', '-r', 'telepresence@localhost:45767', '10.12.87.0/24', '10.12.80.0/24', '10.15.240.0/20', '10.12.82.0/24', '10.12.27.0/24', '10.12.84.0/24', '10.12.88.0/24', '10.12.76.0/24', '10.12.89.0/24', '10.12.81.0/24', '10.12.78.0/24', '10.12.0.0/24', '10.12.83.0/24']...

```

**Comment by ark3** [comment]
Sorry about the crash! How did you install Telepresence? Typically `sshuttle-telepresence` is installed automatically at the same time.

**Comment by nigorice** [comment]
I installed it using `yaourt` https://aur.archlinux.org/packages/telepresence/. I assume the package installer is missing a few bits.

Anyway, I managed to get it running by installing from source. I think I'll close this, thanks again.

**Comment by ark3** [comment]
Glad you're up and running. Keep an eye on #135 for better Arch Linux support, and please help if you can.
