### ISSUE TITLE
Exception in "import socket; socket.gethostbyname('hellotelepresence66')" 

### ISSUE THREAD

**Issue by ddehghan** [datawire/telepresence#609]
### What were you trying to do?

start vpn mode

### What did you expect to happen?

I think it happens when I run the "telepresence --swap-deployment dm-socket-stage --expose 5001" but there are no current pods running for that deployment. That is because they are being started. 

If run telepresence and cancel/ or it dies and it tries to revert back the pod and run telepresence again before that clean up is finished I get this crash consistently.

### What happened instead?

(please tell us - the traceback is automatically included, see below)

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'dm-socket-stage', '--expose', '5001']`
Version: `0.84`
Python version: `3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
kubectl version: `Client Version: v1.10.1 // Server Version: v1.9.4-gke.1`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin DD2.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/telepresence/0.84/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 74, in call_f
    return f(*args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.84/libexec/lib/python3.6/site-packages/telepresence/main.py", line 523, in go_too
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/Cellar/telepresence/0.84/libexec/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/Cellar/telepresence/0.84/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 300, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/Cellar/telepresence/0.84/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 284, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/Cellar/telepresence/0.84/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 261, in get_output
    raise CalledProcessError(cpe_exc.returncode, cpe_exc.cmd, output)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence66')"]' returned non-zero exit status 1.

```

Logs:

```
nodename nor servname provided, or not known
  32.6 TEL | [93] exit 1 in 0.19 secs.
  34.2  26 | c : DNS request from ('2001:569:7c01:7600:d853:38e0:c011:2da9', 41621, 0, 0) to None: 42 bytes
  34.2  26 | c : DNS request from ('2001:569:7c01:7600:d853:38e0:c011:2da9', 31976, 0, 0) to None: 42 bytes
  34.3  16 | 2018-04-23T09:40:43+0000 [stdout#info] A query: b'notifications.google.com'
  34.3  16 | 2018-04-23T09:40:43+0000 [stdout#info] AAAA query, sending back A instead: b'notifications.google.com'
  34.3  16 | 2018-04-23T09:40:43+0000 [stdout#info] A query: b'notifications.google.com'
  34.3  16 | 2018-04-23T09:40:43+0000 [stdout#info] Result for b'notifications.google.com' is ['74.125.141.101', '74.125.141.113', '74.125.141.139', '74.125.141.102', '74.125.141.100', '74.125.141.138']
  34.3  16 | 2018-04-23T09:40:43+0000 [stdout#info] Result for b'notifications.google.com' is ['74.125.141.138', '74.125.141.101', '74.125.141.113', '74.125.141.139', '74.125.141.102', '74.125.141.100']

```

**Comment by ark3** [comment]
This may be a little better in the next release thanks to #605.

**Comment by ddehghan** [comment]
cool. sounds good.
