### ISSUE TITLE
Hang at "Starting proxy..."

### ISSUE THREAD

**Issue by ark3** [datawire/telepresence#83]
In the guestbook example directory, I ran

    $ telepresence --deployment telepresence-deployment --expose 8080 --run-shell
    Starting proxy...

... and it is sitting there.

Log file says:
```
Running: (['docker', 'run', '--rm', '--name', 'telepresence-1491325324-79-46205', '-t', '-v', '/Users/ark3:/opt:ro', '-v', '/Users/ark3:/Users/ark3:ro', '-p', ':9050', '-v', '/tmp/tmpQhUaSJ:/output', 'datawire/telepresence-local:0.23', '501', 'telepresence-deployment', '8080', '10.12.108.229', 'null'],)
Unable to find image 'datawire/telepresence-local:0.23' locally
0.23: Pulling from datawire/telepresence-local
0a8490d0dfd3: Pulling fs layer
51f9c8ec365f: Pulling fs layer
00f17031bf5f: Pulling fs layer
00f17031bf5f: Verifying Checksum
00f17031bf5f: Download complete
0a8490d0dfd3: Verifying Checksum
0a8490d0dfd3: Download complete
0a8490d0dfd3: Pull complete
51f9c8ec365f: Verifying Checksum
51f9c8ec365f: Download complete
51f9c8ec365f: Pull complete
00f17031bf5f: Pull complete
Digest: sha256:96c6330bacca0c60c521ac2a4f8ed829574db665dac9c05824a444960069c9dd
Status: Downloaded newer image for datawire/telepresence-local:0.23
Unable to connect to the server: dial tcp 192.168.64.5:8443: i/o timeout
Traceback (most recent call last):
  File "/usr/local/bin/entrypoint.py", line 348, in <module>
    loads(argv[5])
  File "/usr/local/bin/entrypoint.py", line 320, in main
    remote_info = get_remote_info(deployment_name, namespace)
  File "/usr/local/bin/entrypoint.py", line 153, in get_remote_info
    "--export",
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', 'get', 'deployment', '-o', 'json', 'telepresence-deployment', '--export']' returned non-zero exit status 1
```

**Comment by ark3** [comment]
Ack, the `kubectl` command might be failing because it doesn't see the shell's environment, which has `KUBECONFIG` set.

**Comment by ark3** [comment]
To clarify, this issue is about the fact that telepresence did not notice the failure from `kubectl`.

**Comment by ark3** [comment]
Here's a different log with the same effective result (hang at "Starting Proxy..."). This timeout is due to the telepresence pod not starting, but rather sitting in the pending state. Amazon EC2's burstable CPU instances don't seem to play well with Kubernetes.

```
Running: (['docker', 'run', '--rm', '--name', 'telepresence-1491331609-082925-30608', '-t', '-v', '/home/ubuntu:/opt:ro', '-v', '/home/ubuntu:/home/ubuntu:ro', '-p', ':9050', '-v', '/tmp/tmpzs6wv0b3:/output', 'datawire/telepresence-local:0.23', '1000', 'telepresence-deployment', '8080', '172.31.79.126', 'null'],)
Expected metadata for pods: {'creationTimestamp': None, 'labels': {'tier': 'backend', 'app': 'guestbook'}}
Checking {'tier': 'backend', 'app': 'redis', 'pod-template-hash': '343230949', 'role': 'master'} (phase Running)...
Labels don't match.
Checking {'tier': 'backend', 'app': 'redis', 'pod-template-hash': '132015689', 'role': 'slave'} (phase Running)...
Labels don't match.
Checking {'tier': 'backend', 'app': 'redis', 'pod-template-hash': '132015689', 'role': 'slave'} (phase Running)...
Labels don't match.
Checking {'tier': 'backend', 'app': 'guestbook', 'pod-template-hash': '3802065084'} (phase Pending)...
Looks like we've found our pod!
Traceback (most recent call last):
  File "/usr/local/bin/entrypoint.py", line 348, in <module>
    loads(argv[5])
  File "/usr/local/bin/entrypoint.py", line 320, in main
    remote_info = get_remote_info(deployment_name, namespace)
  File "/usr/local/bin/entrypoint.py", line 192, in get_remote_info
    return RemoteInfo(namespace, deployment_name, name, deployment)
  File "/usr/local/bin/entrypoint.py", line 59, in __init__
    wait_for_pod(self)
  File "/usr/local/bin/entrypoint.py", line 260, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'phase': 'Pending', 'conditions': [{'reason': 'Unschedulable', 'lastProbeTime': None, 'type': 'PodScheduled', 'status': 'False', 'lastTransitionTime': '2017-04-04T18:44:06Z'}]}
Running: (['docker', 'ps', '-q', '--filter', 'name=telepresence-1491331609-082925-30608'],)
```
